version: "3"
   
services:
  client:
    build: .
    image: viteapp:0.0.1
    container_name: "vite-app"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./vue-map:/app
      - /app/node_modules
